// List of Romanian cities (major + common medical hubs)
export const ROMANIAN_CITIES = [
  'București',
  'Cluj-Napoca',
  'Timișoara',
  'Iași',
  'Constanța',
  'Craiova',
  'Brașov',
  'Galați',
  'Ploiești',
  'Oradea',
  'Arad',
  'Sibiu',
  'Bacău',
  'Târgu Mureș',
  'Baia Mare',
  'Satu Mare',
  'Bistrița',
  'Suceava',
  'Botoșani',
  'Piatra Neamț',
  'Vaslui',
  'Focșani',
  'Brăila',
  'Tulcea',
  'Slobozia',
  'Călărași',
  'Giurgiu',
  'Alexandria',
  'Turnu Măgurele',
  'Slatina',
  'Râmnicu Vâlcea',
  'Târgu Jiu',
  'Drobeta-Turnu Severin',
  'Reșița',
  'Deva',
  'Hunedoara',
  'Alba Iulia',
  'Zalău',
  'Carei',
  'Sighetu Marmației',
  'Mediaș',
  'Sighișoara',
  'Făgăraș',
]
